# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-14 10:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='project',
            table='project',
        ),
    ]
