# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-14 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20161214_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='d3_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
