# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-14 11:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_d3_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
        migrations.AlterModelTable(
            name='project',
            table=None,
        ),
    ]
