# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-19 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_smiles_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='compounds',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
