# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-23 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_compounds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='data_file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
