# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-24 19:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('projects', '0008_auto_20161223_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
        migrations.AddField(
            model_name='project',
            name='session',
            field=models.ForeignKey(default=datetime.datetime(2016, 12, 24, 19, 32, 56, 270040, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, to='sessions.Session'),
            preserve_default=False,
        ),
    ]
