# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-30 13:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20161230_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sessions.Session'),
        ),
    ]
