# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-07 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20161230_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='header',
            field=models.TextField(blank=True, null=True),
        ),
    ]
