# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-22 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_project_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='example',
            field=models.BooleanField(default=False),
        ),
    ]
