# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-18 12:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_auto_20170414_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 18, 12, 56, 37, 696635, tzinfo=utc)),
        ),
    ]
